name: CI for Pull Request

on: 
  pull_request:
    branches: [ master ]
    
jobs:
  # Purpose of the process
  build_app_and_run_tests:

    runs-on: ubuntu-latest

    steps:
    # Download superx repo to the runner
    - uses: actions/checkout@v2
    # Set up Python 3.8
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install Environment & Dependencies
      run: |
        apt update
        apt install python3.8 python3-pip python3.8-ven -y
        pip3 install virtualenv
        virtualenv superx --python=python3.8
        source superx/bin/activate
        pip3 install flask Flask-SQLAlchemy Flask-Bootstrap SQLAlchemy flask_login flask_wtf pymysql pytest requests pylint
        export FLASK_APP=superx/app.py
        export FLASK_ENV=development
        flask run -h 0.0.0.0 -p 5000

    - name: Run tests
      run: |
        pytest superx

    - name: Analyse the code with pylint
      run: |
        pylint superx
