name: CI for Pull Request

on: 
  pull_request:
    branches: [ master ]
    
jobs:
  # Purpose of the process
  build:

    runs-on: ubuntu-latest

    steps:
    # Download superx repo to the runner
    - uses: actions/checkout@v2
    # Set up Python 3.8
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install Environment & Dependencies
      run: |
        ./bootstrap.sh

    - name: Run tests
      run: |
        ls
        source venv/bin/activate  
        cd superx 
        echo 'second ls'  
        ls  
        python -m pytest

    - name: Analyse the code with pylint
      run: |
        pylint superx
