name: CI for Pull Request

on: 
  pull_request:
    branches: [ master ]
    
jobs:
  # Purpose of the process
  build app and run tests:

    runs-on: ubuntu-latest

    steps:
    # Download superx repo to the runner
    - uses: actions/checkout@v2
    # Set up Python 3.8
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install Dependencies
      run: |
        pip install flask Flask-SQLAlchemy Flask-Bootstrap SQLAlchemy flask_login flask_wtf pymysql pytest email-validator pylint flake8

    - name: Run tests
      run: |
        pytest superx

    - name: Analyse the code with pylint
      run: |
        pylint superx

  
        
      
        
        
    